name: ark_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipywidgets
  - tqdm
  - numpy
  - pandas
  - xarray
  - scipy
  - scikit-image
  - matplotlib
  - seaborn
  - jupyterlab-lsp
  - python-lsp-server[all]
  - jupyterlab-git
  - jupyterlab_execute_time
  - pip:
    - jupyterlab-skip-traceback
    - lckr-jupyterlab-variableinspector
    - alpineer==0.1.7
    - pyFlowSOM==0.1.15
    - .
