name: ark_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - jupyterlab
  - ipywidgets
  - tqdm
  - numpy
  - pandas
  - xarray
  - scipy
  - scikit-image
  - matplotlib
  - seaborn
  - pip:
    - alpineer==0.1.6
    - pyFlowSOM==0.1.14
    - .
