# takes different masks generated by different versions/runs of deepcell and compares them

import numpy as np
import os
import matplotlib.pyplot as plt
import skimage.io as io

image_dir = '/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/Contours/First_Run/cnn_data/Deepcell_docker/output/Point1_12_18_23_3X'
plot_dir = '/Users/noahgreenwald/Documents/Grad_School/Lab/Segmentation_Project/Contours/First_Run/Figs/'
data = np.zeros((8,4,1024,1024,4) , dtype='float32')

files = os.listdir(image_dir)
files.sort()
files = files[1:len(files)]

# axes on data: training run, image, x_dim, y_dim, output_mask
for i in range(len(files)):
    data[i, :, :, :, :] = np.load(os.path.join(image_dir, files[i]))


# save images back to folder for viewing
names = files
names = [x.replace('Point1_12_18_3X_', '').replace('_epoch_metrics.npy', '') for x in names]
for i in range(len(files)):
    io.imsave(os.path.join(plot_dir, names[i] + '.tiff'), data[i, 3, :, :, 1])


skimage.io.imshow(data[5, 3, :, :, 1])
skimage.io.imsave(plot_dir + 'test_image.tiff', x)
