name: Test

on:
  workflow_call:
    inputs:
      debug_enabled:
        type: boolean
        required: false
        default: false

permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      # Ensure that if any job fails, all jobs are cancelled.
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    env:
      GITHUB_WORKSPACE: ${{ github.workspace }}
      cache-name: dataset-cache

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Example Dataset Cache
        uses: actions/cache/restore@v4
        with:
          path: ./data/cache/
          key: huggingface-${{ env.cache-name }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      
      - name: Install uv and setup Python
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          uv sync --frozen --extra test

      - name: Run Tests
        run: |
          uv run pytest --cov-report=lcov:coverage-${{ join(matrix.*, '-') }}.lcov

      - name: Archive Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ join(matrix.*, '-') }}
          path: |
            coverage-${{ join(matrix.*, '-') }}.lcov
